Description: >
  Felix Lutze / Capstone Project
  Creates two individual hosts to manage the EKS-Cluster

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone-project
    Type: String
  SSHKeyName:
    Description: SSH key for management access
    Default: udacity
    Type: String
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-0767046d1677be5a0
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-management-SG
      GroupDescription: Allow port 22 for management
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  managementHost1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management1
        - Key: Project
          Value: !Ref EnvironmentName

  managementHost2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management2
        - Key: Project
          Value: !Ref EnvironmentName
