Description: >
  Production environment for Capstone-Project

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: capstone-prod
      GroupDescription: Allow port 22 and port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 6443
          ToPort: 6443
          CidrIp: { "Fn::GetAtt" : [ "Default", "CidrBlock" ] }

  k8master:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: ami-0767046d1677be5a0
      Tags:
        - Key: Name
          Value: capstone-k8-master
        - Key: Project
          Value: capstone-project

  k8worker1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: ami-0767046d1677be5a0
      Tags:
        - Key: Name
          Value: capstone-k8-worker1
        - Key: Project
          Value: capstone-project

  k8worker2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: ami-0767046d1677be5a0
      Tags:
        - Key: Name
          Value: capstone-k8-worker2
        - Key: Project
          Value: capstone-project
