- name: "Copy deployment configuration"
  copy:
    src: capstone-deployment.yaml
    dest: $HOME

- name: "Apply deployment configuration"
  command: kubectl apply -f capstone-deployment.yaml
  args:
    chdir: $HOME
