---

- name: "Configuration of K8"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    pre_tasks:
      - name: "Wait 30 seconds for target connection to become reachable/usable."
        command: sleep 30s
  roles:
    - update-server
    - install-docker
    - install-k8
#    - configure-k8
