---
- name: "General configuration"
  hosts: all
  user: ubuntu
  gather_facts: false
  become: yes
  pre_tasks:
    - name: Disable SWAP in fstab
      lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

  roles:
    - install-docker
    - install-kubernetes

- name: "Configure k8 master"
  hosts: master
  user: ubuntu
  gather_facts: false
  tasks:
    - name: "initialize the cluster"
      become: yes
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16

    - name: "create .kube directory"
      shell: mkdir -p $HOME/.kube

    - name: "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
      become: yes
      shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

    - name: "chown $(id -u):$(id -g) $HOME/.kube/config"
      become: yes
      shell: chown $(id -u):$(id -g) $HOME/.kube/config

    - name: "Apply a Flannel networking plugin"
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

##  Configure k8 workers ##

- name: "Store join command"
  hosts: master
  user: ubuntu
  gather_facts: false
  become: yes
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: "Apply join command"
  hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
