- name: "Deploy latest app"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_BUILD_NUM: "{{ lookup('env', 'CIRCLE_BUILD_NUM') }}"
  tasks:
    - name: Update the deployment to run the latest Build
      shell: "./bin/kubectl set image deployments/{{ ENVIRONMENT_NAME }}-deployment {{ ENVIRONMENT_NAME }}-app=felixlutze/{{ ENVIRONMENT_NAME }}:{{ CIRCLE_BUILD_NUM }}"
      args:
        chdir: $HOME

    - name: Check if deployment ist successful
      shell: "./bin/kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}-deployment"
      args:
        chdir: $HOME
