- name: "GPG key for the official Docker repository"
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: "Docker repository to APT sources"
  command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: "update packages"
  apt:
    update_cache: yes

- name: "Install from the Docker repo instead of the default Ubuntu repo"
  command: apt-cache policy docker-ce

- name: "install dependencies"
  apt:
    name: [ "apt-transport-https", "ca-certificates", "curl", "software-properties-common", "gzip" , "docker-ce"]
    state: latest
    update_cache: yes
