apiVersion: v1
kind: Service
metadata:
  name: capstone-loadbalancer
  labels:
    app: capstone-app
spec:
  selector:
    app: capstone-app
  type: LoadBalancer
  ports:
  - nodePort: 30000
    port: 8080
    targetPort: 8080
